#!/usr/bin/env node
// cloudflare-setup.js
// Sets up Cloudflare integration for TV Launcher.
//
// Mode A — Named Tunnel (preferred, permanent):
//   Requires token with "Cloudflare Tunnel: Edit" permission.
//   Creates a named tunnel → permanent URL, no DNS changes on restart.
//
// Mode B — Quick Tunnel + DNS (automatic fallback):
//   Requires token with "DNS: Edit" permission only.
//   Uses cloudflared quick tunnel + updates CNAME on every start.
//   TV is always accessible at your custom domain (e.g. tv.snakesponsor.com).
//
// Usage:
//   CF_API_TOKEN=your_token node cloudflare-setup.js
//   CF_API_TOKEN=your_token CF_DOMAIN=tv.example.com node cloudflare-setup.js

'use strict';
const fs   = require('fs');
const path = require('path');

const CF_API = 'https://api.cloudflare.com/client/v4';
const TOKEN  = process.env.CF_API_TOKEN || '';
const DOMAIN = (process.env.CF_DOMAIN || '').trim();
const PORT   = 8765;

if (!globalThis.fetch) {
  console.error('Node.js 18+ required. Current:', process.version);
  process.exit(1);
}
if (!TOKEN) {
  console.error('\n  CF_API_TOKEN env var required.\n');
  process.exit(1);
}

async function api(method, endpoint, body) {
  const res = await fetch(`${CF_API}${endpoint}`, {
    method,
    headers: { Authorization: `Bearer ${TOKEN}`, 'Content-Type': 'application/json' },
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  const data = await res.json();
  if (!data.success) {
    const code = data.errors?.[0]?.code;
    const msg  = data.errors?.map((e) => `[${e.code}] ${e.message}`).join('; ') || `HTTP ${res.status}`;
    const err  = new Error(msg);
    err.code   = code;
    throw err;
  }
  return data.result;
}

function writeEnv(pairs) {
  const envPath = path.join(__dirname, '.env');
  const existing = fs.existsSync(envPath)
    ? fs.readFileSync(envPath, 'utf8')
    : '';
  const lines = existing.split('\n').filter(l => l && l.startsWith('#') === false);
  const map = Object.fromEntries(
    lines.map(l => l.split('=').map((p, i) => i === 0 ? p : l.slice(p.length + 1)))
         .filter(([k]) => k)
  );
  Object.assign(map, pairs);

  const out = [
    '# Auto-generated by cloudflare-setup.js — DO NOT COMMIT',
    ...Object.entries(map).map(([k, v]) => `${k}=${v}`),
  ].join('\n') + '\n';
  fs.writeFileSync(envPath, out);
}

async function main() {
  console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log(' TV Launcher — Cloudflare Setup');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

  // 1. Get account
  const accounts = await api('GET', '/accounts?per_page=1');
  if (!accounts.length) throw new Error('No Cloudflare accounts found.');
  const account = accounts[0];
  console.log(`✓  Account: ${account.name}`);

  // 2. Find DNS zone for domain
  let zone = null;
  if (DOMAIN) {
    const root = DOMAIN.split('.').slice(-2).join('.');
    const zones = await api('GET', `/zones?name=${root}&per_page=1`);
    if (zones.length) {
      zone = zones[0];
      console.log(`✓  Zone: ${zone.name}  (${zone.id})`);
    } else {
      console.warn(`⚠  Zone "${root}" not in your account — DNS step will be skipped.`);
    }
  }

  // 3. Try Named Tunnel (needs "Cloudflare Tunnel: Edit")
  let mode = 'dns'; // default fallback
  let tunnelToken = null;
  let tunnelId    = null;

  try {
    const existing = await api(
      'GET', `/accounts/${account.id}/cfd_tunnel?name=tv-launcher&is_deleted=false`,
    );
    let tunnel;
    if (existing.length) {
      tunnel = existing[0];
      console.log(`✓  Reusing tunnel: ${tunnel.id}`);
    } else {
      tunnel = await api('POST', `/accounts/${account.id}/cfd_tunnel`, {
        name: 'tv-launcher', config_src: 'cloudflare',
      });
      console.log(`✓  Created tunnel: ${tunnel.id}`);
    }
    tunnelId = tunnel.id;

    // Ingress
    const ingress = [];
    if (DOMAIN) ingress.push({ hostname: DOMAIN, service: `http://localhost:${PORT}` });
    ingress.push({ service: `http://localhost:${PORT}` });
    await api('PUT', `/accounts/${account.id}/cfd_tunnel/${tunnel.id}/configurations`, {
      config: { ingress },
    });

    // Token
    tunnelToken = await api('GET', `/accounts/${account.id}/cfd_tunnel/${tunnel.id}/token`);
    mode = 'named';
    console.log(`✓  Tunnel token retrieved`);
  } catch (e) {
    if (e.code === 10000) {
      console.log(`ℹ  Tunnel API not available (token needs "Cloudflare Tunnel: Edit").`);
      console.log(`   Falling back to Quick Tunnel + DNS mode.`);
    } else {
      throw e;
    }
  }

  // 4. DNS CNAME (both modes if zone available)
  const effectiveUrl = DOMAIN ? `https://${DOMAIN}` : null;

  if (zone && DOMAIN && mode === 'named' && tunnelId) {
    // Named tunnel: point CNAME to tunnel's cfargotunnel.com address (permanent)
    const cname = `${tunnelId}.cfargotunnel.com`;
    await upsertCNAME(zone.id, DOMAIN, cname, true);
    console.log(`✓  DNS CNAME (permanent): ${DOMAIN} → tunnel`);
  } else if (zone && DOMAIN && mode === 'dns') {
    // Quick tunnel mode: CNAME will be updated on every start-tunnel.sh run
    // Create a placeholder so the record exists (will be overwritten at startup)
    await upsertCNAME(zone.id, DOMAIN, 'placeholder.trycloudflare.com', true);
    console.log(`✓  DNS placeholder created — will update on each tunnel start`);
  }

  // 5. Write .env
  const envData = {
    CF_ACCOUNT_ID: account.id,
    CF_TUNNEL_MODE: mode,
  };
  if (zone && DOMAIN) {
    envData.CF_ZONE_ID = zone.id;
    envData.CF_DOMAIN  = DOMAIN;
  }
  if (effectiveUrl)  envData.TUNNEL_URL    = effectiveUrl;
  if (tunnelToken)   envData.TUNNEL_TOKEN  = tunnelToken;
  if (tunnelId)      envData.CF_TUNNEL_ID  = tunnelId;

  writeEnv(envData);
  console.log(`✓  Saved .env`);

  // 6. Summary
  console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  if (mode === 'named') {
    console.log(` Mode       : Named Tunnel (permanent)`);
    if (effectiveUrl) console.log(` Public URL : ${effectiveUrl}`);
    console.log(` Start      : bash start-tunnel.sh --token`);
  } else {
    console.log(` Mode       : Quick Tunnel + DNS (updates on each start)`);
    if (effectiveUrl) console.log(` Domain     : ${effectiveUrl}  ✓ always works`);
    console.log(` Start      : bash start-tunnel.sh`);
    console.log('');
    console.log(' To upgrade to named tunnel, edit your API token to add:');
    console.log('   Cloudflare Tunnel: Edit  (Account scope)');
    console.log('   then re-run: node cloudflare-setup.js');
  }
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
}

async function upsertCNAME(zoneId, name, content, proxied) {
  const records = await api('GET', `/zones/${zoneId}/dns_records?type=CNAME&name=${name}&per_page=1`);
  if (records.length) {
    await api('PATCH', `/zones/${zoneId}/dns_records/${records[0].id}`, { content, proxied });
  } else {
    await api('POST', `/zones/${zoneId}/dns_records`, { type: 'CNAME', name, content, proxied });
  }
}

main().catch((e) => { console.error(`\n✗  ${e.message}\n`); process.exit(1); });
